blank_issues_enabled: false
contact_links:
  - name: ðŸ¤” Help & Questions
    url: https://community.auth0.com/c/sdks/5
    about: Ask general support or usage questions in the Auth0 Community forums
  - name: ðŸ“‘ FAQ
    url: https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md
    about: Check some commonly asked questions
  - name: ðŸš€ Examples
    url: https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md
    about: Check the examples to get up to speed with the SDK
  - name: ðŸ“– API Documentation
    url: https://auth0.github.io/nextjs-auth0/
    about: Check the public API documentation for in-depth overview of all the available features
